import * as XLSX from 'xlsx';

/**
 * Generates a base64 Data URL for downloadable Excel (.xlsx) files
 */
export function generateExcelExport(sheetName, dataRows) {
  try {
    const worksheet = XLSX.utils.json_to_sheet(dataRows);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName || 'IPO Ledger Data');
    
    const wbout = XLSX.write(workbook, { bookType: 'xlsx', type: 'base64' });
    return `data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,${wbout}`;
  } catch (err) {
    console.error('Error generating Excel export:', err);
    return null;
  }
}

/**
 * Generates an HTML printable PDF Data URL for official statements & reports
 */
export function generatePDFExport(title, summaryText, headers, rows) {
  try {
    const headerHtml = headers.map(h => `<th style="padding:10px;border:1px solid #334155;background:#1e293b;color:#34d399;text-align:left;">${h}</th>`).join('');
    const rowsHtml = rows.map(row => 
      `<tr style="border-bottom:1px solid #334155;">${row.map(cell => `<td style="padding:8px;border:1px solid #334155;color:#f8fafc;">${cell}</td>`).join('')}</tr>`
    ).join('');

    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #090d16; color: #f8fafc; padding: 30px; line-height: 1.5; }
    .header { text-align: center; border-bottom: 2px solid #10b981; padding-bottom: 15px; margin-bottom: 20px; }
    .title { font-size: 22px; font-weight: bold; color: #10b981; }
    .subtitle { font-size: 12px; color: #94a3b8; margin-top: 5px; }
    .summary-card { background: #1e293b; border-radius: 8px; padding: 15px; margin-bottom: 20px; border: 1px solid #334155; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 12px; }
    .footer { margin-top: 30px; font-size: 11px; color: #64748b; text-align: center; border-top: 1px solid #334155; padding-top: 15px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">📈 IPO Pro Ledger - ${title}</div>
    <div class="subtitle">Generated on ${new Date().toLocaleString()} | Official System Audit</div>
  </div>
  <div class="summary-card">
    ${summaryText}
  </div>
  <table>
    <thead><tr>${headerHtml}</tr></thead>
    <tbody>${rowsHtml}</tbody>
  </table>
  <div class="footer">
    Official report generated by IPO Pro Ledger AI Assistant. Confidential & Authenticated.
  </div>
</body>
</html>`;

    return `data:text/html;charset=utf-8,${encodeURIComponent(htmlContent)}`;
  } catch (err) {
    console.error('Error generating PDF export:', err);
    return null;
  }
}
